// News Source
export const SET_SOURCE_LOADING = "SET_SOURCE_LOADING";
export const GET_NEWS_SOURCE = "GET_NEWS_SOURCE";
export const NEWS_SOURCE_ERROR = "NEWS_SOURCE_ERROR";
// News
export const SET_NEWS_LOADING = "SET_NEWS_LOADING";
export const SET_TOP_NEWS = "SET_TOP_NEWS";
export const CLEAR_TOP_NEWS = "CLEAR_TOP_NEWS";
export const TOP_NEWS_ERROR = "TOP_NEWS_ERROR";
// Bookmark
export const BOOKMARK_ITEM = "BOOKMARK_ITEM";
export const UNBOOKMARK_ITEM = "UNBOOKMARK_ITEM";
export const GET_BOOKMARK_ITEMS = "GET_BOOKMARK_ITEMS";

export const SIGNIN_USER_REQUEST = "SIGNIN_USER_REQUEST";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR";

export const SIGNOUT_USER_REQUEST = "SIGNOUT_USER_REQUEST";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const SIGNOUT_USER_ERROR = "SIGNOUT_USER_ERROR";
